#pragma once
#pragma warning(disable : 4244 4267 4018 4305 4309 4804 4365 4311 4312)
#define IMGUI_DEFINE_MATH_OPERATORS
#include <d3d11.h>
#include <tchar.h>
#include <TlHelp32.h>
#include <intrin.h>
#include <windows.h>
#include <wincrypt.h>
#include <iostream>
#include <shlwapi.h>
#include <Wbemidl.h>
#include <regex>
#include <psapi.h>
#include <string>
#include <vector>
#include <functional>
#include "imgui.h"
#include "imgui_internal.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"
#include "strenc.h"
#include "encrypt.hh"
#include "http.h"
#include "minhook/MinHook.h"
#include "seguranca.h"
#include "icon.h"
#include "Bytes.h"
#include "Utils.h"
#include "imwindow.h"
